const express=require("express"),session=require("express-session"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),path=require("path"),fs=require("fs");
const app=express(),PORT=process.env.PORT||3000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;if(!ADMIN_PASSWORD){console.error("Missing ADMIN_PASSWORD");process.exit(1)}
const dataDir=path.join(__dirname,"data");fs.mkdirSync(dataDir,{recursive:true});const db=new Database(path.join(dataDir,"the-era.sqlite"));db.pragma("journal_mode=WAL");db.exec(`CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL,pin TEXT NOT NULL,payment TEXT NOT NULL,upi_id TEXT DEFAULT "",items_json TEXT NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'NEW',created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS admin_users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL);`);if(!db.prepare("SELECT id FROM admin_users WHERE username=?").get("owner")){db.prepare("INSERT INTO admin_users(username,password_hash) VALUES(?,?)").run("owner",bcrypt.hashSync(ADMIN_PASSWORD,12))}
app.use(express.json({limit:"100kb"}));app.use(express.urlencoded({extended:false}));app.use(session({secret:process.env.SESSION_SECRET||"change-this-session-secret",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:43200000}}));
const products={"baggy-combo":{name:"Baggy Combo",price:1480},"baggy-black-denim":{name:"Baggy Black Light Washed Denim",price:899},"slim-yellow-stripe-shirt":{name:"Slim Fit Yellow Stripe Shirt",price:599}};const auth=(req,res,next)=>req.session.admin?next():res.status(401).json({error:"Unauthorized"});
app.post("/api/orders",(req,res)=>{try{const {customer,payment,upiId,items}=req.body||{};if(!customer?.name||!customer?.phone||!customer?.email||!customer?.address||!customer?.city||!/^\d{6}$/.test(customer?.pin||""))return res.status(400).json({error:"Please complete all delivery details."});if(!["cod","upi"].includes(payment))return res.status(400).json({error:"Invalid payment method."});if(payment==="upi"&&!upiId)return res.status(400).json({error:"UPI ID is required."});if(!Array.isArray(items)||!items.length)return res.status(400).json({error:"Your cart is empty."});let total=0,clean=[];for(const item of items){const p=products[item.id],qty=Math.max(1,Math.min(20,parseInt(item.qty,10)||0));if(!p)return res.status(400).json({error:"Invalid product."});total+=p.price*qty;clean.push({id:item.id,name:p.name,price:p.price,qty})}const orderId="ERA"+Date.now().toString().slice(-8),createdAt=new Date().toISOString();db.prepare(`INSERT INTO orders(order_id,name,phone,email,address,city,pin,payment,upi_id,items_json,total,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(orderId,customer.name,customer.phone,customer.email,customer.address,customer.city,customer.pin,payment,upiId||"",JSON.stringify(clean),total,"NEW",createdAt);res.status(201).json({order:{orderId,items:clean,total,payment,createdAt,status:"NEW"}})}catch(e){console.error(e);res.status(500).json({error:"Could not place order."})}});
app.post("/admin/login",(req,res)=>{const user=db.prepare("SELECT * FROM admin_users WHERE username=?").get("owner");if(!user||!bcrypt.compareSync(String(req.body.password||""),user.password_hash))return res.status(401).json({error:"Incorrect owner password."});req.session.admin=true;res.json({ok:true})});app.post("/admin/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/admin/orders",auth,(req,res)=>{const {search="",date="",status=""}=req.query;let sql="SELECT * FROM orders WHERE 1=1",p=[];if(status){sql+=" AND status=?";p.push(status)}if(date){sql+=" AND date(created_at)=?";p.push(date)}if(search){sql+=" AND (order_id LIKE ? OR name LIKE ? OR phone LIKE ? OR email LIKE ? OR items_json LIKE ?)";const q="%"+search+"%";p.push(q,q,q,q,q)}sql+=" ORDER BY datetime(created_at) DESC";const rows=db.prepare(sql).all(...p).map(r=>({orderId:r.order_id,name:r.name,phone:r.phone,email:r.email,address:r.address,city:r.city,pin:r.pin,payment:r.payment,upiId:r.upi_id,items:JSON.parse(r.items_json),total:r.total,status:r.status,createdAt:r.created_at}));const stats={total:db.prepare("SELECT COUNT(*) c FROM orders").get().c,new:db.prepare("SELECT COUNT(*) c FROM orders WHERE status='NEW'").get().c,delivered:db.prepare("SELECT COUNT(*) c FROM orders WHERE status='DELIVERED'").get().c,revenue:db.prepare("SELECT COALESCE(SUM(total),0) s FROM orders WHERE status!='CANCELLED'").get().s};res.json({orders:rows,stats})});
app.patch("/api/admin/orders/:id/status",auth,(req,res)=>{const allowed=["NEW","CONFIRMED","SHIPPED","DELIVERED","CANCELLED"],status=req.body.status;if(!allowed.includes(status))return res.status(400).json({error:"Invalid status"});const r=db.prepare("UPDATE orders SET status=? WHERE order_id=?").run(status,req.params.id);if(!r.changes)return res.status(404).json({error:"Order not found"});res.json({ok:true})});
app.get("/admin",auth,(req,res)=>res.sendFile(path.join(__dirname,"public","admin.html")));app.use(express.static(path.join(__dirname,"public")));app.listen(PORT,()=>console.log(`THE ERA running on http://localhost:${PORT}`));
