
const { neon } = require("@neondatabase/serverless");
const PRODUCTS={
"baggy-combo":{name:"Baggy Combo",price:1480,sizes:["S","M","L","XL"]},
"baggy-black-denim":{name:"Baggy Black Light Washed Denim",price:899,sizes:["S","M","L","XL"]},
"slim-yellow-stripe-shirt":{name:"Slim Fit Yellow Stripe Shirt",price:599,sizes:["S","M","L","XL"]},
"relaxed-oxford-shirt":{name:"Relaxed Oxford Shirt",price:699,sizes:["S","M","L","XL"]},
"knit-polo":{name:"Textured Knit Polo",price:749,sizes:["S","M","L","XL"]},
"pleated-trousers":{name:"Wide-Leg Pleated Trousers",price:999,sizes:["S","M","L","XL"]},
"boxy-tee":{name:"Heavyweight Boxy Tee",price:499,sizes:["S","M","L","XL"]},
"utility-overshirt":{name:"Utility Overshirt",price:899,sizes:["S","M","L","XL"]}
};
function db(){const u=process.env.DATABASE_URL||process.env.STORAGE_DATABASE_URL;if(!u)throw new Error("Neon database connection is not configured.");return neon(u)}
async function schema(d){await d`CREATE TABLE IF NOT EXISTS orders(id BIGSERIAL PRIMARY KEY,order_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL,pin TEXT NOT NULL,payment TEXT NOT NULL,upi_id TEXT DEFAULT '',items_json JSONB NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'NEW',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
module.exports=async(req,res)=>{try{if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});const b=req.body||{},c=b.customer||{},items=b.items||[],pay=b.payment,upi=b.upiId||"";if(!c.name||!c.phone||!c.email||!c.address||!c.city||!/^\d{6}$/.test(String(c.pin||"")))return res.status(400).json({error:"Please complete all delivery details."});if(!["cod","upi"].includes(pay))return res.status(400).json({error:"Invalid payment method."});if(pay==="upi"&&!upi)return res.status(400).json({error:"UPI ID is required."});if(!items.length)return res.status(400).json({error:"Your cart is empty."});let total=0,clean=[];for(const i of items){const p=PRODUCTS[i.id],qty=Math.max(1,Math.min(20,parseInt(i.qty,10)||0));if(!p)return res.status(400).json({error:"Invalid product."});const size=p.sizes.includes(i.size)?i.size:"M";total+=p.price*qty;clean.push({id:i.id,name:p.name,price:p.price,qty,size})}const d=db();await schema(d);const oid="ERA"+Date.now().toString().slice(-8);const rows=await d`INSERT INTO orders(order_id,name,phone,email,address,city,pin,payment,upi_id,items_json,total,status) VALUES(${oid},${String(c.name).trim()},${String(c.phone).trim()},${String(c.email).trim()},${String(c.address).trim()},${String(c.city).trim()},${String(c.pin).trim()},${pay},${upi},${JSON.stringify(clean)},${total},'NEW') RETURNING order_id,total,payment,status,created_at`;return res.status(201).json({order:{orderId:rows[0].order_id,items:clean,total:rows[0].total,payment:rows[0].payment,status:rows[0].status,createdAt:rows[0].created_at}})}catch(e){console.error("ORDER ERROR:",e);return res.status(500).json({error:"A server error occurred while placing the order."})}}
